# Ch02 NumPy basic operation 

In [1]:
import numpy as np

In [6]:
# 版本確認
np.__version__

'2.1.3'

## 陣列索引與切片 (Indexing & Slicing)

### 1D array

In [2]:
x = np.array([-3, 4, 6, 9, 8, 3]); x

array([-3,  4,  6,  9,  8,  3])

In [6]:
# 指定索引
print(x)
x[0]

[-3  4  6  9  8  3]


np.int64(-3)

In [7]:
# 切片 (範圍: [start, end-1, step])
print(x)
x[0:2] # index 0 ~ 2 的值

[-3  4  6  9  8  3]


array([-3,  4])

In [8]:
# 切片，指定每幾步算一次
'''
這樣也可以
x[::2]
'''
print(x)
x[0:5:2]

[-3  4  6  9  8  3]


array([-3,  6,  8])

In [ ]:
# 切片 (使用負號)
print(x)
x[-1] # 最後一個index

[-3  4  6  9  8  3]


np.int64(3)

In [ ]:
# 切片 (範圍: [start, end-1, step])
print(x)
x[-3:-1] # 倒數第3-1個到最後一個index

[-3  4  6  9  8  3]


array([9, 8])

### 2D array

In [12]:
x2 = np.array([[2,3,4],
               [9,8,7],
               [11,12,13]]); 
print(x2)

[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]


In [ ]:
print(x2)
x2[1,1]

[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]


np.int64(8)

In [16]:
# Retrieve row 2
print(x2)
x2[2] # x2[2] = x2[2,]

[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]


array([11, 12, 13])

In [22]:
print(x2)
x2[2, :] # : 全部元素

[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]


array([11, 12, 13])

In [23]:
# Retrieve column 1
print(x2)
x2[ : , 1]

[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]


array([ 3,  8, 12])

In [ ]:
print(x2)
x2[1:,::2] # row:從index開始取到最後，col:從0開始到最後，step=2

[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]


array([[ 9,  7],
       [11, 13]])

## 塑型 reshape

In [27]:
x2

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [ ]:
# reshape 改變陣列形狀，不改變數值
x2.reshape(9,1)

array([[ 2],
       [ 3],
       [ 4],
       [ 9],
       [ 8],
       [ 7],
       [11],
       [12],
       [13]])

In [ ]:
# reshape
x2.reshape(1,9)

array([[ 2,  3,  4,  9,  8,  7, 11, 12, 13]])

### Fancy indexing

 一般而言如果我希望將python list 中的元素 分割後重新再組合成新的 list 該怎麼做??

In [ ]:
lst = [1, 2, 3, 4, 5, 6]

lst_new = [] # 想要創建一個新的 lst 為[1, 3, 5]

lst_new.append(lst[0])
lst_new.append(lst[2])
lst_new.append(lst[4])

print(lst_new)

[1, 3, 5]


In [ ]:
np.random.seed(42)
x = np.random.randint(100 , size=10) # 100以內隨機取10個整數
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74], dtype=int32)

In [ ]:
# access three different elements
# 取三個元素 組成一個list
print(x)
lst = [x[3], x[7], x[2]]

# 這是一般 python numpy array 切割資料的方法 來重新組成 python list
print(lst)
print(type(lst))

[51 92 14 71 60 20 82 86 74 74]
[np.int32(71), np.int32(86), np.int32(14)]
<class 'list'>


In [32]:
# fancy index
# 陣列中 放陣列格式
arr1 = x[[3,7,2]]

print(arr1)
print(type(arr1))

[71 86 14]
<class 'numpy.ndarray'>


### 效能測試

In [33]:
x2

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [34]:
x2[1,2]

np.int64(7)

In [35]:
x2[1][2]

np.int64(7)

In [ ]:
%timeit x2[1,2] # %timeit 要花多久時間

75.9 ns ± 6.04 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [37]:
%timeit x2[1][2]
#速度慢

159 ns ± 1.5 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [38]:
# summary for vector
vec = np.array([-3, 4, 6, 9, 8, 3]) # 1D vector
print("vec - 4th value:", vec[3])

vec[3] = 19
print("vec - 4th value (changed):", vec[3])

# summary for matrix
mat = np.array([
    [2, 4, 6, 8],
    [10, 12, 14, 16]
])
print("mat - 1st row:", mat[0])
print("mat - 2nd row's 1st value:", mat[1, 0])
print("mat - last row's last value:", mat[-1, -1])

vec - 4th value: 9
vec - 4th value (changed): 19
mat - 1st row: [2 4 6 8]
mat - 2nd row's 1st value: 10
mat - last row's last value: 16


## 陣列的遮罩

In [48]:
np.random.seed(5)
ar=np.random.randint(0,25,10); ar

array([ 3, 14, 15,  6, 22, 16,  9,  8,  4,  7], dtype=int32)

In [55]:
# 取出可以被2整除的數
print(ar)
print(ar[ar % 2 == 0])

[ 3 14 15  6 22 16  9  8  4  7]
[14  6 22 16  8  4]


In [ ]:
evenMask=(ar%2==0); evenMask # 生成遮罩

array([False,  True, False,  True,  True,  True, False,  True,  True,
       False])

In [ ]:
evenNums=ar[evenMask]; evenNums # 用遮罩 所以ar的內容不會變

array([14,  6, 22, 16,  8,  4], dtype=int32)

## 陣列的串接

In [37]:
# 陣列結合
'''
numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
'''

x = np.array([1,2,3])
y = np.array([11,22,33])

z = np.concatenate((x, y)); z

print(x)

print(y)

[1 2 3]
[11 22 33]


In [38]:
# 將陣列元素加入其它陣列
z = np.concatenate((x, [12, 14, 16])); z

array([ 1,  2,  3, 12, 14, 16])

### Vertical Stacking 堆疊

In [ ]:

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

print(arr1)
print("---------")
print(arr2)

# Vertical stack them
np.vstack((arr1, arr2))



[[1 2]
 [3 4]]
---------
[[5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

### Horizontal Stacking

In [43]:
# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print(arr1)
print("---------")
print(arr2)

# Horizontal stack them
np.hstack((arr1, arr2))



[[1 2]
 [3 4]]
---------
[[5 6]
 [7 8]]


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## 陣列的複製 np.copy()

In [45]:
arr = np.arange(8); arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
arr_copy = arr.copy(); arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
# check memory id

print("arr 記憶體位址: ", id(arr))
print("arr_copy 記憶體位址: ", id(arr_copy))

arr 記憶體位址:  2792987016816
arr_copy 記憶體位址:  2792987017104


In [48]:
arr_copy[0] = -1

print("before copy: ", arr)
print("after copy: ", arr_copy)


before copy:  [0 1 2 3 4 5 6 7]
after copy:  [-1  1  2  3  4  5  6  7]


## 陣列指定索引插入元素 insert()

In [49]:
# 在陣列指定索引 2 插入元素 9
'''
numpy.insert(arr, obj, values, axis=None)
'''
x = np.array([2,4,6,8,10])

z = np.insert(x, 2, 9); z

array([ 2,  4,  9,  6,  8, 10])

In [50]:
# 在陣列指定索引 1 跟 3，分別插入元素 7 跟 9
x = np.array([2,4,6,8,10])

z = np.insert(x, [1,3], [7,9]); z

array([ 2,  7,  4,  6,  9,  8, 10])

## 刪除指定索引的陣列元素 delete()

In [51]:
# 刪除索引 1 的元素
'''
numpy.delete(arr, obj, axis=None)
'''
x = np.array([2,4,6,8,10])

z = np.delete(x, 1); z

array([ 2,  6,  8, 10])

In [52]:
# 刪除索引 1 和 3 所放置的元素
x = np.array([2,4,6,8,10])

z = np.delete(x, [1, 3]); z

array([ 2,  6, 10])